author: "hubin@CSDC"
login:
  user: 
    label: "Username"
    value: "username"
    disabled: true
  sns: 
    label: "SNS Code"
    value: "sns"
    disabled: true
  oidc:
    label: "OIDC"
    value: "oidc"
    providers:
      - name: "Cognito"
        iconUrl: "cognito"
        description: "AWS's built-in user authentication service"
        region: "us-east-1"
        clientId: "ug1oiijdio1e92rfrptd9jg75"  
        userPoolId: "us-east-1_PaWe18vwE"
      - name: "Authing"
        iconUrl: "authing"
        description: "Authentication service for ensuring application security"
      - name: "Okta"
        iconUrl: "okta"
        description: "A service that focuses on identity and access management"
  third:
    - type: "google"
      iconUrlSelected: "google_in"
      iconUrl: "google"
      iconStyle: {"width":39,"marginTop":-2}
    - type: "facebook"
      iconUrlSelected: "facebook_in"
      iconUrl: "facebook"
      iconStyle: {"width":34}
    - type: "linkedin"
      iconUrlSelected: "linkedin_in"
      iconUrl: "linkedin"
      iconStyle: {"width":35}
  